### ISSUE TITLE
Importing RotatedRegion3 issues

### ISSUE THREAD

**Issue by Xuleos** [OverHash/Roblox-TS-Libraries#1]
`import { RotatedRegion3 } from "@rbxts/rotatedregion3";` 
will compile as 
`local RotatedRegion3 = TS.import(script, TS.getModule(script, "rotatedregion3")).RotatedRegion3`
due to the way things are exported in the type definitions

As you can see, this will pretty much guarantee an error in game as RotatedRegion3 is not a member of the RotatedRegion3 class.

**Comment by Xuleos** [comment]
#2

**Comment by OverHash** [comment]
Closed via #2
