### ISSUE TITLE
RotatedRegion3.Block is not a callback

### ISSUE THREAD

**Issue by rwilliaise** [OverHash/Roblox-TS-Libraries#16]
After thoroughly confusing @OverHash and myself with #15, I have found the true problem with the code:

https://github.com/OverHash/Roblox-TS-Libraries/blob/5447b402e073c273f415aa2f8b23062a57ae88a8/RotatedRegion3/index.d.ts#L43

The static method `RotatedRegion3#Block` is not treated as a callback, even though the rest of the methods are.

Sorry!

**Comment by OverHash** [comment]
Oops! Thanks for spotting this!

**Comment by OverHash** [comment]
Fixed!

```bash
npm install @rbxts/rotatedregion3@1.2.0
```
