### ISSUE TITLE
Janitor types don't seem to support passing true for MethodName

### ISSUE THREAD

**Issue by Xuleos** [OverHash/Roblox-TS-Libraries#9]
janitor types hate me and are trying to force me to study for my french quiz tomorrow instead of working on a roblox game

`Janitor.Add(() => {}, true)` errors with `"Argument of type 'true' is not assignable to parameter of type '((this: () => void) => void) | ((_: () => void) => void) | undefined'"`

**Comment by OverHash** [comment]
Fixed in 9c759dbe2f740023581f47a9d2156802824fbdf7
